-- Supericons MCP usage ledger
--
-- Purpose:
-- - Keep hosted MCP usage visible in the local admin dashboard.
-- - Preserve the existing search_request_audit table while adding optional
--   attribution fields for channel, environment, client family, and tool name.
-- - Store only hashed or generic client identifiers. No raw IP address,
--   user-agent string, prompt, or API key is stored.
--
-- Rollback plan:
-- - To disable the new ledger, stop writing mcp_usage_events from the hosted
--   MCP server first, then drop the mcp_usage_events indexes and table.
-- - The added search_request_audit columns are optional. Leave them in place
--   for compatibility unless a later migration confirms no released server
--   version still writes them.

alter table if exists public.search_request_audit
  add column if not exists channel text,
  add column if not exists environment text,
  add column if not exists client_family text,
  add column if not exists tool_name text,
  add column if not exists locale text,
  add column if not exists anonymous_client_hash text,
  add column if not exists user_agent_hash text,
  add column if not exists api_key_hash text,
  add column if not exists mcp_server_version text,
  add column if not exists request_id text,
  add column if not exists dedupe_key text;

create index if not exists search_request_audit_channel_created_at_idx
  on public.search_request_audit (channel, created_at desc)
  where channel is not null;

create index if not exists search_request_audit_environment_created_at_idx
  on public.search_request_audit (environment, created_at desc)
  where environment is not null;

create index if not exists search_request_audit_client_family_created_at_idx
  on public.search_request_audit (client_family, created_at desc)
  where client_family is not null;

create table if not exists public.mcp_usage_events (
  id bigint generated by default as identity primary key,
  event_id text not null default md5(random()::text || clock_timestamp()::text),
  request_id text,
  dedupe_key text,
  event_type text not null,
  channel text not null default 'unknown',
  environment text not null default 'production',
  client_family text not null default 'unknown',
  tool_name text,
  query_norm text,
  library_filter text,
  result_count integer,
  status text not null default 'ok',
  latency_ms integer,
  country_code text,
  geo_source text,
  locale text,
  anonymous_client_hash text,
  session_hash text,
  ip_hash text,
  user_agent_hash text,
  api_key_hash text,
  user_id uuid references auth.users(id) on delete set null,
  is_registered boolean not null default false,
  is_pro boolean not null default false,
  account_plan text,
  subscription_status text,
  mcp_server_version text,
  search_request_audit_id bigint references public.search_request_audit(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb,
  constraint mcp_usage_events_channel_check check (
    channel in ('web', 'hosted_mcp', 'local_mcp', 'cli', 'api', 'internal_test', 'unknown')
  ),
  constraint mcp_usage_events_environment_check check (
    environment in ('production', 'preview', 'local', 'test', 'legacy')
  ),
  constraint mcp_usage_events_status_check check (
    status in ('ok', 'error', 'fallback', 'skipped')
  ),
  constraint mcp_usage_events_result_count_check check (
    result_count is null or result_count >= 0
  ),
  constraint mcp_usage_events_latency_ms_check check (
    latency_ms is null or latency_ms >= 0
  ),
  constraint mcp_usage_events_country_code_check check (
    country_code is null or country_code ~ '^[A-Z]{2}$'
  )
);

create unique index if not exists mcp_usage_events_dedupe_key_idx
  on public.mcp_usage_events (dedupe_key)
  where dedupe_key is not null;

create index if not exists mcp_usage_events_created_at_idx
  on public.mcp_usage_events (created_at desc);

create index if not exists mcp_usage_events_channel_created_at_idx
  on public.mcp_usage_events (channel, created_at desc);

create index if not exists mcp_usage_events_environment_created_at_idx
  on public.mcp_usage_events (environment, created_at desc);

create index if not exists mcp_usage_events_tool_created_at_idx
  on public.mcp_usage_events (tool_name, created_at desc)
  where tool_name is not null;

create index if not exists mcp_usage_events_query_created_at_idx
  on public.mcp_usage_events (query_norm, created_at desc)
  where query_norm is not null;

create index if not exists mcp_usage_events_client_created_at_idx
  on public.mcp_usage_events (anonymous_client_hash, created_at desc)
  where anonymous_client_hash is not null;

alter table public.mcp_usage_events enable row level security;

revoke all on table public.mcp_usage_events from anon, authenticated;
grant select, insert, update, delete on table public.mcp_usage_events to service_role;
grant usage, select on sequence public.mcp_usage_events_id_seq to service_role;

comment on table public.mcp_usage_events is
  'Private service-role ledger for hosted MCP usage attribution and admin reporting.';
comment on column public.mcp_usage_events.anonymous_client_hash is
  'Hashed client grouping value. Raw IP address and raw user-agent are not stored.';
comment on column public.mcp_usage_events.api_key_hash is
  'Hashed API key identifier when available. Raw API keys are never stored.';
