-- Final search outcome telemetry.
--
-- Rollback plan, written before implementation:
-- 1. Set search_telemetry_settings.dashboard_source to legacy.
-- 2. Set search_telemetry_settings.web_ingestion_enabled to false.
-- 3. Drop the MCP copy trigger so new MCP events stop entering the final ledger.
-- 4. Keep every final outcome, diagnostic, cutover timestamp, and linkage column.
-- 5. Restore the Local MCP suppression only through its separate rollback file.
-- 6. Website and MCP search continue because every telemetry write is best effort.
--
-- Backward compatibility:
-- - Existing search_request_audit and mcp_usage_events writers keep working.
-- - No existing column is renamed, removed, or made more restrictive.
-- - Existing rows are not assigned manufactured episode or attempt identities.
-- - The dashboard remains on its legacy source until a later guarded cutover.

begin;

create table if not exists public.search_final_outcomes (
  id bigint generated by default as identity primary key,
  contract_version integer not null default 1,
  episode_id uuid not null,
  recovery_chain_id uuid,
  source_event_id text,
  channel text not null,
  query text not null,
  environment text not null,
  traffic_class text not null,
  client_family text not null default 'unknown',
  tool_name text,
  library_filter text,
  library_mode text,
  style text,
  locale text,
  final_match_count integer not null,
  final_outcome text not null,
  settlement_state text not null,
  search_execution text,
  server_build text,
  diagnostic_attempt_count integer,
  legacy_identity_quality text not null default 'exact',
  source_version text,
  anonymous_client_hash text,
  user_id uuid references auth.users(id) on delete set null,
  is_registered boolean not null default false,
  client_ip_public boolean not null default false,
  country_code text,
  geo_source text,
  completed_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb,
  constraint search_final_outcomes_contract_version_valid check (contract_version >= 1),
  constraint search_final_outcomes_episode_unique unique (episode_id),
  constraint search_final_outcomes_channel_valid check (
    channel in ('web', 'hosted_mcp', 'local_mcp')
  ),
  constraint search_final_outcomes_query_valid check (
    char_length(trim(query)) between 1 and 500
  ),
  constraint search_final_outcomes_environment_valid check (
    environment in ('production', 'preview', 'local', 'test', 'legacy')
  ),
  constraint search_final_outcomes_traffic_class_valid check (
    traffic_class in ('controlled_test', 'preview', 'local', 'named_cohort', 'unclassified_live')
  ),
  constraint search_final_outcomes_library_mode_valid check (
    library_mode is null or library_mode in ('strict', 'prefer', 'all')
  ),
  constraint search_final_outcomes_style_valid check (
    style is null or style in ('any', 'outline', 'solid')
  ),
  constraint search_final_outcomes_match_count_valid check (final_match_count >= 0),
  constraint search_final_outcomes_final_outcome_valid check (
    final_outcome in ('success', 'zero', 'error')
  ),
  constraint search_final_outcomes_settlement_state_valid check (
    settlement_state in ('completed', 'failed')
  ),
  constraint search_final_outcomes_attempt_count_valid check (
    diagnostic_attempt_count is null or diagnostic_attempt_count >= 0
  ),
  constraint search_final_outcomes_identity_quality_valid check (
    legacy_identity_quality in ('exact', 'legacy_best_effort')
  ),
  constraint search_final_outcomes_country_code_valid check (
    country_code is null or country_code ~ '^[A-Z]{2}$'
  ),
  constraint search_final_outcomes_outcome_count_consistent check (
    (final_outcome = 'success' and final_match_count > 0)
    or (final_outcome in ('zero', 'error') and final_match_count = 0)
  ),
  constraint search_final_outcomes_settlement_consistent check (
    (final_outcome = 'error' and settlement_state = 'failed')
    or (final_outcome = 'zero' and settlement_state = 'completed')
    or (final_outcome = 'success' and settlement_state in ('completed', 'failed'))
  )
);

create unique index if not exists search_final_outcomes_source_event_unique
  on public.search_final_outcomes (source_event_id)
  where source_event_id is not null;

create index if not exists search_final_outcomes_completed_at_idx
  on public.search_final_outcomes (completed_at desc);

create index if not exists search_final_outcomes_channel_completed_at_idx
  on public.search_final_outcomes (channel, completed_at desc);

create index if not exists search_final_outcomes_environment_completed_at_idx
  on public.search_final_outcomes (environment, completed_at desc);

create index if not exists search_final_outcomes_query_completed_at_idx
  on public.search_final_outcomes (query, completed_at desc);

create table if not exists public.search_episode_diagnostics (
  diagnostic_id uuid primary key default gen_random_uuid(),
  contract_version integer not null default 1,
  episode_id uuid not null,
  recovery_chain_id uuid,
  diagnostic_type text not null,
  channel text not null default 'web',
  query text not null,
  local_match_count integer,
  hosted_match_count integer,
  hosted_state text,
  search_execution text,
  error_code text,
  environment text not null,
  traffic_class text not null,
  source_version text,
  observed_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  metadata jsonb not null default '{}'::jsonb,
  constraint search_episode_diagnostics_contract_version_valid check (contract_version >= 1),
  constraint search_episode_diagnostics_episode_type_unique unique (episode_id, diagnostic_type),
  constraint search_episode_diagnostics_type_valid check (
    diagnostic_type in ('superseded', 'incomplete')
  ),
  constraint search_episode_diagnostics_channel_valid check (channel = 'web'),
  constraint search_episode_diagnostics_query_valid check (
    char_length(trim(query)) between 1 and 500
  ),
  constraint search_episode_diagnostics_local_count_valid check (
    local_match_count is null or local_match_count >= 0
  ),
  constraint search_episode_diagnostics_hosted_count_valid check (
    hosted_match_count is null or hosted_match_count >= 0
  ),
  constraint search_episode_diagnostics_hosted_state_valid check (
    hosted_state is null or hosted_state in ('pending', 'success', 'zero', 'error', 'not_started')
  ),
  constraint search_episode_diagnostics_environment_valid check (
    environment in ('production', 'preview', 'local', 'test', 'legacy')
  ),
  constraint search_episode_diagnostics_traffic_class_valid check (
    traffic_class in ('controlled_test', 'preview', 'local', 'named_cohort', 'unclassified_live')
  )
);

create index if not exists search_episode_diagnostics_episode_idx
  on public.search_episode_diagnostics (episode_id, observed_at desc);

create index if not exists search_episode_diagnostics_observed_at_idx
  on public.search_episode_diagnostics (observed_at desc);

create table if not exists public.search_telemetry_settings (
  setting_id text primary key,
  dashboard_source text not null default 'legacy',
  web_ingestion_enabled boolean not null default true,
  web_final_outcome_cutover_at timestamptz,
  local_mcp_coverage_cutover_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint search_telemetry_settings_singleton check (setting_id = 'active'),
  constraint search_telemetry_settings_dashboard_source_valid check (
    dashboard_source in ('legacy', 'shadow', 'final')
  )
);

insert into public.search_telemetry_settings (
  setting_id,
  dashboard_source,
  web_ingestion_enabled
) values (
  'active',
  'legacy',
  true
)
on conflict (setting_id) do nothing;

create table if not exists public.search_telemetry_rate_limits (
  subject_hash text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (subject_hash, window_started_at),
  constraint search_telemetry_rate_limits_subject_valid check (
    subject_hash ~ '^[a-f0-9]{64}$'
  ),
  constraint search_telemetry_rate_limits_count_valid check (request_count >= 0)
);

create index if not exists search_telemetry_rate_limits_updated_at_idx
  on public.search_telemetry_rate_limits (updated_at);

alter table public.search_request_audit
  add column if not exists contract_version integer,
  add column if not exists episode_id uuid,
  add column if not exists recovery_chain_id uuid,
  add column if not exists attempt_id uuid,
  add column if not exists attempt_number integer,
  add column if not exists query_variant text,
  add column if not exists query_origin text,
  add column if not exists search_engine text,
  add column if not exists execution_route text,
  add column if not exists server_build text;

create index if not exists search_request_audit_episode_created_at_idx
  on public.search_request_audit (episode_id, created_at)
  where episode_id is not null;

create unique index if not exists search_request_audit_attempt_unique
  on public.search_request_audit (attempt_id)
  where attempt_id is not null;

create or replace function public.si_try_uuid(p_value text)
returns uuid
language plpgsql
immutable
set search_path = public
as $$
declare
  v_value text := lower(trim(coalesce(p_value, '')));
begin
  if v_value !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    return null;
  end if;
  return v_value::uuid;
exception
  when invalid_text_representation then
    return null;
end;
$$;

create or replace function public.si_capture_mcp_search_final_outcome()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_episode_id uuid;
  v_final_outcome text;
  v_traffic_class text;
  v_query text;
  v_diagnostic_attempt_count integer;
begin
  if new.event_type <> 'search_outcome'
     or new.tool_name not in ('search_icons', 'recommend_icons')
     or new.channel not in ('hosted_mcp', 'local_mcp') then
    return new;
  end if;

  if new.status = 'error' or new.search_outcome = 'error' then
    v_final_outcome := 'error';
  elsif coalesce(new.result_count, 0) > 0 or new.search_outcome = 'results' then
    v_final_outcome := 'success';
  elsif new.search_outcome = 'zero' then
    v_final_outcome := 'zero';
  else
    return new;
  end if;

  v_query := left(trim(coalesce(new.query_norm, '')), 500);
  if v_query = '' then
    return new;
  end if;

  v_episode_id := coalesce(
    public.si_try_uuid(new.metadata ->> 'episode_id'),
    public.si_try_uuid(new.event_id),
    gen_random_uuid()
  );
  select count(*)::integer
  into v_diagnostic_attempt_count
  from public.search_request_audit
  where episode_id = v_episode_id;

  v_traffic_class := lower(trim(coalesce(new.metadata ->> 'traffic_class', '')));
  if v_traffic_class not in (
    'controlled_test',
    'preview',
    'local',
    'named_cohort',
    'unclassified_live'
  ) then
    v_traffic_class := case
      when new.environment = 'test' then 'controlled_test'
      when new.environment = 'preview' then 'preview'
      when new.environment = 'local' then 'local'
      else 'unclassified_live'
    end;
  end if;

  insert into public.search_final_outcomes (
    contract_version,
    episode_id,
    recovery_chain_id,
    source_event_id,
    channel,
    query,
    environment,
    traffic_class,
    client_family,
    tool_name,
    library_filter,
    library_mode,
    locale,
    final_match_count,
    final_outcome,
    settlement_state,
    search_execution,
    server_build,
    diagnostic_attempt_count,
    legacy_identity_quality,
    source_version,
    anonymous_client_hash,
    user_id,
    is_registered,
    client_ip_public,
    country_code,
    geo_source,
    completed_at,
    metadata
  ) values (
    1,
    v_episode_id,
    public.si_try_uuid(new.metadata ->> 'recovery_chain_id'),
    'mcp_usage_events:' || new.id::text,
    case
      when new.channel = 'local_mcp' then 'local_mcp'
      else 'hosted_mcp'
    end,
    v_query,
    case
      when new.environment in ('production', 'preview', 'local', 'test', 'legacy')
        then new.environment
      else 'production'
    end,
    v_traffic_class,
    coalesce(nullif(trim(new.client_family), ''), 'unknown'),
    new.tool_name,
    new.library_filter,
    new.library_mode,
    new.locale,
    case when v_final_outcome = 'success' then greatest(coalesce(new.result_count, 0), 1) else 0 end,
    v_final_outcome,
    case when v_final_outcome = 'error' then 'failed' else 'completed' end,
    nullif(trim(coalesce(new.metadata ->> 'search_execution', '')), ''),
    nullif(trim(coalesce(new.metadata ->> 'server_build', '')), ''),
    v_diagnostic_attempt_count,
    case
      when public.si_try_uuid(new.metadata ->> 'episode_id') is not null
        or public.si_try_uuid(new.event_id) is not null
        then 'exact'
      else 'legacy_best_effort'
    end,
    new.mcp_server_version,
    coalesce(new.anonymous_client_hash, new.session_hash),
    new.user_id,
    new.is_registered,
    coalesce(new.client_ip_public, false),
    new.country_code,
    new.geo_source,
    new.created_at,
    jsonb_build_object(
      'source_table', 'mcp_usage_events',
      'source_row_id', new.id,
      'query_origin', new.query_origin,
      'requested_limit', new.requested_limit,
      'returned_icon_refs', new.metadata -> 'returned_icon_refs',
      'returned_icon_refs_recorded',
      lower(coalesce(new.metadata ->> 'returned_icon_refs_recorded', 'false')) = 'true'
    )
  )
  on conflict do nothing;

  return new;
end;
$$;

drop trigger if exists capture_mcp_search_final_outcome
  on public.mcp_usage_events;

create trigger capture_mcp_search_final_outcome
after insert on public.mcp_usage_events
for each row
execute function public.si_capture_mcp_search_final_outcome();

create or replace function public.si_take_web_search_telemetry_rate_limit(
  p_subject_hash text,
  p_limit integer default 120,
  p_window_seconds integer default 60
)
returns table (
  allowed boolean,
  remaining integer,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subject_hash text := lower(trim(coalesce(p_subject_hash, '')));
  v_limit integer := p_limit;
  v_window_seconds integer := p_window_seconds;
  v_window_start timestamptz;
  v_count integer;
begin
  if v_subject_hash !~ '^[a-f0-9]{64}$' then
    raise exception 'subject_hash must be a sha256 value' using errcode = '22023';
  end if;
  if v_limit < 1 or v_limit > 10000 then
    raise exception 'limit is outside the supported range' using errcode = '22023';
  end if;
  if v_window_seconds < 10 or v_window_seconds > 3600 then
    raise exception 'window_seconds is outside the supported range' using errcode = '22023';
  end if;

  v_window_start := to_timestamp(
    floor(extract(epoch from timezone('utc', now())) / v_window_seconds) * v_window_seconds
  );

  insert into public.search_telemetry_rate_limits (
    subject_hash,
    window_started_at,
    request_count,
    updated_at
  ) values (
    v_subject_hash,
    v_window_start,
    1,
    timezone('utc', now())
  )
  on conflict (subject_hash, window_started_at)
  do update set
    request_count = public.search_telemetry_rate_limits.request_count + 1,
    updated_at = timezone('utc', now())
  returning request_count into v_count;

  if mod(abs(hashtext(v_subject_hash)), 100) = 0 then
    delete from public.search_telemetry_rate_limits
    where updated_at < timezone('utc', now()) - interval '1 day';
  end if;

  return query select
    v_count <= v_limit,
    greatest(v_limit - v_count, 0),
    greatest(
      1,
      ceil(extract(epoch from (v_window_start + make_interval(secs => v_window_seconds) - timezone('utc', now()))))::integer
    );
end;
$$;

alter table public.search_final_outcomes enable row level security;
alter table public.search_episode_diagnostics enable row level security;
alter table public.search_telemetry_settings enable row level security;
alter table public.search_telemetry_rate_limits enable row level security;

revoke all on table public.search_final_outcomes from public, anon, authenticated;
revoke all on table public.search_episode_diagnostics from public, anon, authenticated;
revoke all on table public.search_telemetry_settings from public, anon, authenticated;
revoke all on table public.search_telemetry_rate_limits from public, anon, authenticated;
revoke all on function public.si_try_uuid(text) from public, anon, authenticated;
revoke all on function public.si_capture_mcp_search_final_outcome() from public, anon, authenticated;
revoke all on function public.si_take_web_search_telemetry_rate_limit(text, integer, integer)
  from public, anon, authenticated;

grant select, insert, update, delete on table public.search_final_outcomes to service_role;
grant select, insert, update, delete on table public.search_episode_diagnostics to service_role;
grant select, insert, update on table public.search_telemetry_settings to service_role;
grant select, insert, update, delete on table public.search_telemetry_rate_limits to service_role;
grant usage, select on sequence public.search_final_outcomes_id_seq to service_role;
grant execute on function public.si_take_web_search_telemetry_rate_limit(text, integer, integer)
  to service_role;

comment on table public.search_final_outcomes is
  'Private final product outcomes. One eligible search episode has at most one row.';
comment on table public.search_episode_diagnostics is
  'Private website episode diagnostics for superseded or unresolved search work.';
comment on table public.search_telemetry_settings is
  'Private dashboard cutover and Web ingestion controls for final search telemetry.';
comment on column public.search_final_outcomes.legacy_identity_quality is
  'Exact when the writer supplied a product episode ID, or legacy_best_effort for older Local MCP RPC calls.';

commit;
