-- P0.02 taxonomy seed for the first three job-shaped collections.
-- Source of truth: lib/icon-taxonomy-seed.js

insert into public.icon_metadata (
  icon_id,
  source_library,
  job_category,
  secondary_categories
)
values
  ('si:artificial-analysis', 'si', 'ai-search-research-evaluation', array['model-benchmarking', 'ai-evaluation', 'provider-comparison', 'ai-benchmarking', 'llm-leaderboard']::text[]),
  ('si:base44', 'si', 'ai-app-builders', array['ai-app-builder', 'no-code-low-code', 'vibe-coding', 'text-to-app', 'app-generation']::text[]),
  ('si:bolt', 'si', 'ai-app-builders', array['ai-app-builder', 'browser-app-builder', 'vibe-coding', 'bolt-new', 'web-app-generation']::text[]),
  ('si:bridgemind-ai', 'si', 'coding-agents-dev-environments', array['coding-agent', 'developer-tooling', 'code-assistant', 'ai-development', 'developer-agent', 'code-workflow']::text[]),
  ('si:browserbase', 'si', 'agent-infrastructure-runtime', array['browser-automation', 'web-agent-runtime', 'agent-infrastructure', 'headless-browser', 'web-automation', 'agent-runtime']::text[]),
  ('si:capcut', 'si', 'generative-media-creative-ai', array['video-editing', 'short-form-video', 'creative-ai', 'creator-tools', 'video-editor', 'social-video']::text[]),
  ('si:cartesia', 'si', 'voice-audio-ai', array['voice-ai', 'speech-generation', 'audio-models', 'text-to-speech', 'voice-models', 'real-time-audio']::text[]),
  ('si:cohere', 'si', 'model-platforms-ai-labs', array['enterprise-llm', 'reranking', 'model-api', 'foundation-models', 'embedding-models', 'enterprise-ai']::text[]),
  ('si:context7', 'si', 'mcp-tooling-protocols', array['mcp-docs', 'developer-context', 'tool-protocol', 'context-server', 'developer-docs', 'mcp']::text[]),
  ('si:devin', 'si', 'coding-agents-dev-environments', array['coding-agent', 'software-engineering-agent', 'autonomous-development', 'developer-agent', 'engineering-automation', 'ai-coding']::text[]),
  ('si:exa', 'si', 'ai-search-research-evaluation', array['ai-search', 'web-search-api', 'research-retrieval', 'semantic-search', 'web-retrieval', 'research-api']::text[]),
  ('si:factory-ai', 'si', 'coding-agents-dev-environments', array['coding-agent', 'software-development', 'engineering-automation', 'developer-agent', 'ai-engineering', 'code-automation']::text[]),
  ('si:fal-ai', 'si', 'generative-media-creative-ai', array['image-video-generation', 'model-inference', 'creative-api', 'media-models', 'inference-api', 'creative-infrastructure']::text[]),
  ('si:firecrawl', 'si', 'agent-infrastructure-runtime', array['web-crawling', 'agent-ingestion', 'data-extraction', 'web-scraping', 'site-ingestion', 'agent-data']::text[]),
  ('si:glama', 'si', 'mcp-tooling-protocols', array['mcp-directory', 'tool-discovery', 'agent-tools', 'mcp', 'tool-registry', 'agent-tooling']::text[]),
  ('si:google-ai-studio', 'si', 'model-platforms-ai-labs', array['model-studio', 'gemini', 'prompt-prototyping', 'google-ai', 'model-prototyping', 'ai-studio']::text[]),
  ('si:google-antigravity', 'si', 'coding-agents-dev-environments', array['agentic-ide', 'coding-agent', 'developer-environment', 'google-ai', 'developer-workspace', 'ai-coding']::text[]),
  ('si:goose', 'si', 'general-agents-assistants', array['local-agent', 'desktop-agent', 'task-automation', 'agent-assistant', 'local-automation', 'multi-step-agent']::text[]),
  ('si:hermes-agent', 'si', 'general-agents-assistants', array['general-agent', 'browser-agent', 'task-agent', 'autonomous-agent', 'ai-assistant', 'agent-worker']::text[]),
  ('si:heygen', 'si', 'generative-media-creative-ai', array['avatar-video', 'synthetic-video', 'ai-video', 'video-generation', 'avatar-generation', 'creative-ai']::text[]),
  ('si:higgsfield', 'si', 'generative-media-creative-ai', array['ai-video', 'motion-generation', 'creative-ai', 'video-generation', 'image-to-video', 'cinematic-ai']::text[]),
  ('si:inngest', 'si', 'agent-infrastructure-runtime', array['workflow-orchestration', 'durable-functions', 'event-driven-agents', 'background-jobs', 'agent-workflows', 'workflow-engine']::text[]),
  ('si:kickbacks-ai', 'si', 'agent-business-monetization', array['affiliate-monetization', 'agent-commerce', 'referrals', 'revenue-tools', 'agent-marketplace', 'affiliate-ai']::text[]),
  ('si:kilo-code', 'si', 'coding-agents-dev-environments', array['coding-agent', 'open-source-ide', 'developer-agent', 'ai-coding', 'code-assistant', 'developer-workspace']::text[]),
  ('si:kimi', 'si', 'model-platforms-ai-labs', array['chat-assistant', 'long-context', 'foundation-model', 'model-platform', 'llm-assistant', 'ai-lab']::text[]),
  ('si:kling-ai', 'si', 'generative-media-creative-ai', array['ai-video', 'image-to-video', 'generative-media', 'video-generation', 'creative-ai', 'synthetic-video']::text[]),
  ('si:lovable', 'si', 'ai-app-builders', array['ai-app-builder', 'vibe-coding', 'web-app-generation', 'text-to-app', 'product-builder', 'frontend-generation']::text[]),
  ('si:luma-ai', 'si', 'generative-media-creative-ai', array['ai-video', '3d-generation', 'creative-ai', 'dream-machine', 'video-generation', 'world-model']::text[]),
  ('si:manus-ai', 'si', 'general-agents-assistants', array['general-agent', 'autonomous-agent', 'multi-step-tasks', 'ai-assistant', 'agent-worker', 'task-automation']::text[]),
  ('si:mobbin', 'si', 'design-ui-intelligence', array['design-inspiration', 'ui-reference', 'product-design', 'screen-library', 'design-research', 'ui-patterns']::text[]),
  ('si:openai-codex-app', 'si', 'coding-agents-dev-environments', array['coding-agent', 'software-engineering-agent', 'developer-environment', 'ai-coding', 'developer-agent', 'code-generation']::text[]),
  ('si:openclaw', 'si', 'general-agents-assistants', array['general-agent', 'open-source-agent', 'desktop-agent', 'autonomous-agent', 'agent-assistant', 'local-agent']::text[]),
  ('si:opencode', 'si', 'coding-agents-dev-environments', array['terminal-coding-agent', 'developer-cli', 'coding-agent', 'ai-coding', 'command-line-agent', 'code-assistant']::text[]),
  ('si:pika', 'si', 'generative-media-creative-ai', array['ai-video', 'generative-video', 'creative-ai', 'video-generation', 'text-to-video', 'synthetic-video']::text[]),
  ('si:pinecone', 'si', 'agent-infrastructure-runtime', array['vector-database', 'retrieval-memory', 'agent-memory', 'embeddings', 'semantic-retrieval', 'rag-infrastructure']::text[]),
  ('si:pixverse', 'si', 'generative-media-creative-ai', array['ai-video', 'generative-video', 'creative-ai', 'video-generation', 'text-to-video', 'synthetic-video']::text[]),
  ('si:portkey', 'si', 'agent-infrastructure-runtime', array['ai-gateway', 'llm-observability', 'model-routing', 'model-gateway', 'ai-observability', 'llm-routing']::text[]),
  ('si:runway', 'si', 'generative-media-creative-ai', array['ai-video', 'creative-studio', 'generative-media', 'video-generation', 'film-tools', 'synthetic-media']::text[]),
  ('si:shadcn-ui', 'si', 'design-ui-intelligence', array['ui-components', 'design-system', 'frontend-ui', 'component-library', 'interface-building']::text[]),
  ('si:smithery', 'si', 'mcp-tooling-protocols', array['mcp-directory', 'mcp-server-hosting', 'tool-registry', 'mcp', 'agent-tools', 'server-directory']::text[]),
  ('si:stagehand', 'si', 'agent-infrastructure-runtime', array['browser-automation', 'web-agent-runtime', 'agent-testing', 'web-automation', 'browser-agent', 'agent-runtime']::text[]),
  ('si:stepfun', 'si', 'model-platforms-ai-labs', array['foundation-model', 'chat-assistant', 'model-platform', 'llm', 'ai-lab', 'model-api']::text[]),
  ('si:suno-ai', 'si', 'voice-audio-ai', array['music-generation', 'audio-generation', 'voice-audio-ai', 'ai-music', 'song-generation', 'audio-models']::text[]),
  ('si:supericons', 'si', 'design-ui-intelligence', array['ai-icon-library', 'design-assets', 'ui-icons', 'icon-system', 'brand-icons', 'design-tooling']::text[]),
  ('si:temporal', 'si', 'agent-infrastructure-runtime', array['durable-workflows', 'workflow-orchestration', 'agent-runtime', 'workflow-engine', 'long-running-tasks', 'reliable-execution']::text[]),
  ('si:trae', 'si', 'coding-agents-dev-environments', array['agentic-ide', 'coding-agent', 'developer-environment', 'ai-coding', 'developer-workspace', 'code-assistant']::text[]),
  ('si:vercel-eve', 'si', 'agent-infrastructure-runtime', array['agent-runtime', 'web-agent', 'deployment-platform', 'ai-agent', 'vercel-platform', 'web-runtime']::text[]),
  ('si:x-ai', 'si', 'model-platforms-ai-labs', array['foundation-model', 'grok', 'grok-imagine', 'ai-lab', 'model-provider', 'llm', 'image-generation', 'video-generation', 'xai']::text[]),
  ('si:xiaomi-mimo', 'si', 'model-platforms-ai-labs', array['foundation-model', 'edge-ai', 'ai-lab', 'model-provider', 'mobile-ai', 'xiaomi-ai']::text[]),
  ('si:z-ai', 'si', 'model-platforms-ai-labs', array['foundation-model', 'open-model', 'ai-lab', 'model-provider', 'llm', 'zai']::text[]),
  ('si:agent-commit', 'si', 'coding-agent-tools', array['developer-tools', 'version-control', 'git', 'save']::text[]),
  ('si:agent-diff', 'si', 'coding-agent-tools', array['developer-tools', 'version-control', 'patch', 'change']::text[]),
  ('si:agent-face', 'si', 'agent-lifecycle-states', array['status-feedback', 'communication', 'bot', 'avatar', 'assistant']::text[]),
  ('si:agent-handoff', 'si', 'agent-lifecycle-states', array['multi-agent', 'agent-state', 'delegate', 'transfer']::text[]),
  ('si:agent-id-badge', 'si', 'agent-trust-safety', array['governance', 'developer-tools', 'identity', 'scope']::text[]),
  ('si:agent-pr', 'si', 'coding-agent-tools', array['developer-tools', 'version-control', 'git', 'review']::text[]),
  ('si:agent-swarm', 'si', 'agent-workflow-mcp', array['multi-agent', 'architecture', 'mesh', 'cluster']::text[]),
  ('si:agent-wallet', 'si', 'agentic-payments', array['crypto', 'governance', 'funds', 'account']::text[]),
  ('si:approval-gate', 'si', 'agent-lifecycle-states', array['security', 'agent-state', 'consent', 'pause']::text[]),
  ('si:ar-glasses', 'si', 'frontier-compute', array['hardware-devices', 'wearable', 'xr']::text[]),
  ('si:autonomy-dial', 'si', 'agent-trust-safety', array['governance', 'ui-controls', 'delegation', 'level']::text[]),
  ('si:bison-yeet', 'si', 'trending-culture', array['humor', 'meme', 'surprise', 'yeet']::text[]),
  ('si:context-gauge', 'si', 'agent-workflow-mcp', array['analytics', 'developer-tools', 'window', 'capacity']::text[]),
  ('si:cybertruck', 'si', 'cars-vehicles', array['trending-culture', 'ev', 'tesla', 'truck']::text[]),
  ('si:cybertruck-low', 'si', 'cars-vehicles', array['trending-culture', 'ev', 'tesla', 'truck']::text[]),
  ('si:cybertruck-solid', 'si', 'cars-vehicles', array['trending-culture', 'ev', 'tesla', 'truck']::text[]),
  ('si:delivery-robot', 'si', 'physical-automation', array['hardware-devices', 'commerce', 'sidewalk', 'parcel']::text[]),
  ('si:done-spark', 'si', 'agent-lifecycle-states', array['agent-state', 'complete', 'success']::text[]),
  ('si:drone-delivery', 'si', 'physical-automation', array['hardware-devices', 'commerce', 'parcel', 'drop']::text[]),
  ('si:drone-quad', 'si', 'physical-automation', array['hardware-devices', 'uav', 'fpv']::text[]),
  ('si:edge-ai-chip', 'si', 'frontier-compute', array['hardware-devices', 'developer-tools', 'edge-ai', 'chip', 'hardware']::text[]),
  ('si:entangled-pair', 'si', 'frontier-compute', array['science', 'linked', 'correlated']::text[]),
  ('si:error-glitch', 'si', 'agent-lifecycle-states', array['agent-state', 'fault', 'alert']::text[]),
  ('si:guardrail-path', 'si', 'agent-trust-safety', array['agent-state', 'governance', 'bounds', 'policy']::text[]),
  ('si:hallucination-warn', 'si', 'agent-trust-safety', array['status-feedback', 'governance', 'distortion', 'verify']::text[]),
  ('si:human-in-loop', 'si', 'agent-trust-safety', array['governance', 'agent-state', 'oversight', 'review']::text[]),
  ('si:humanoid-robot', 'si', 'physical-automation', array['robotics', 'hardware-devices', 'humanoid', 'hardware']::text[]),
  ('si:lidar-sensor', 'si', 'physical-automation', array['hardware-devices', 'scan', 'range']::text[]),
  ('si:loader-orbit', 'si', 'agent-lifecycle-states', array['loading-states', 'agent-state', 'loading', 'spinner']::text[]),
  ('si:machine-pay', 'si', 'agentic-payments', array['crypto', 'multi-agent', 'm2m', 'autonomous']::text[]),
  ('si:mcp-connector', 'si', 'agent-workflow-mcp', array['mcp', 'developer-tools', 'plug', 'server']::text[]),
  ('si:memory-store', 'si', 'agent-workflow-mcp', array['data', 'agent-state', 'context', 'recall']::text[]),
  ('si:orchestrator', 'si', 'agent-workflow-mcp', array['multi-agent', 'architecture', 'supervisor']::text[]),
  ('si:person-airborne', 'si', 'trending-culture', array['humor', 'meme', 'fail', 'yeet']::text[]),
  ('si:person-launched', 'si', 'trending-culture', array['humor', 'meme', 'launch', 'speed']::text[]),
  ('si:pipeline-run', 'si', 'agent-workflow-mcp', array['architecture', 'developer-tools', 'workflow', 'chain']::text[]),
  ('si:plan-branches', 'si', 'agent-workflow-mcp', array['agent-state', 'developer-tools', 'tasks', 'decompose']::text[]),
  ('si:progress-ring', 'si', 'agent-lifecycle-states', array['loading-states', 'analytics', 'progress', 'task']::text[]),
  ('si:prompt-field', 'si', 'agent-workflow-mcp', array['ui-controls', 'communication', 'input', 'ask']::text[]),
  ('si:prompt-injection', 'si', 'agent-trust-safety', array['developer-tools', 'governance', 'attack', 'input']::text[]),
  ('si:quantum-chip', 'si', 'frontier-compute', array['hardware-devices', 'science', 'qpu', 'processor']::text[]),
  ('si:qubit-sphere', 'si', 'frontier-compute', array['hardware-devices', 'science', 'bloch', 'state']::text[]),
  ('si:retry-route', 'si', 'agent-lifecycle-states', array['agent-state', 'status-feedback', 'recover', 'reroute']::text[]),
  ('si:robot-arm', 'si', 'physical-automation', array['hardware-devices', 'manipulator', 'industrial']::text[]),
  ('si:robot-dog', 'si', 'physical-automation', array['hardware-devices', 'quadruped', 'patrol']::text[]),
  ('si:sandbox-run', 'si', 'coding-agent-tools', array['security', 'developer-tools', 'isolated', 'safe']::text[]),
  ('si:skill-module', 'si', 'agent-workflow-mcp', array['developer-tools', 'mcp', 'plugin', 'capability']::text[]),
  ('si:spend-limit', 'si', 'agentic-payments', array['crypto', 'governance', 'cap', 'policy']::text[]),
  ('si:stablecoin', 'si', 'agentic-payments', array['crypto', 'peg', 'currency']::text[]),
  ('si:streaming-caret', 'si', 'agent-lifecycle-states', array['status-feedback', 'loading-states', 'typing', 'response']::text[]),
  ('si:terminal-agent', 'si', 'coding-agent-tools', array['developer-tools', 'cli', 'shell']::text[]),
  ('si:thinking-pulse', 'si', 'agent-lifecycle-states', array['status-feedback', 'loading-states', 'agent-state', 'thinking', 'reasoning', 'loading-state']::text[]),
  ('si:token-meter', 'si', 'agent-workflow-mcp', array['analytics', 'developer-tools', 'usage', 'budget']::text[]),
  ('si:tool-call', 'si', 'agent-workflow-mcp', array['mcp', 'developer-tools', 'function', 'invoke']::text[]),
  ('si:voice-agent', 'si', 'frontier-compute', array['communication', 'hardware-devices', 'speech', 'waveform']::text[]),
  ('si:x402-pay', 'si', 'agentic-payments', array['crypto', 'developer-tools', 'protocol', 'http']::text[]),
  ('si:agent-scout', 'si', 'agent-identity', array['agent-lifecycle-states', 'people-accounts', 'bot', 'explorer', 'chatbot', 'avatar']::text[]),
  ('si:agent-wink', 'si', 'agent-identity', array['agent-lifecycle-states', 'people-accounts', 'bot', 'friendly', 'companion', 'avatar']::text[]),
  ('si:game-pad', 'si', 'game-assets', array['devices-hardware', 'media-playback', 'controller', 'play', 'gaming', 'console']::text[]),
  ('si:game-ghost', 'si', 'game-assets', array['trending-culture', 'enemy', 'sprite', 'arcade', 'npc']::text[]),
  ('si:toothpaste', 'si', 'everyday-objects', array['health-body', 'trending-culture', 'dental', 'hygiene', 'teeth', 'routine']::text[]),
  ('si:bacteria', 'si', 'health-body', array['frontier-compute', 'germ', 'microbe', 'pathogen', 'microbiology']::text[]),
  ('si:stomach', 'si', 'health-body', array['gut', 'digestion', 'organ', 'anatomy']::text[]),
  ('si:lawn-mower', 'si', 'physical-automation', array['everyday-objects', 'mower', 'grass', 'gardening', 'yard']::text[]),
  ('si:house-key', 'si', 'everyday-objects', array['security-access', 'maps-places-travel', 'key', 'home', 'real-estate', 'property']::text[]),
  ('si:screw', 'si', 'everyday-objects', array['fastener', 'hardware', 'diy', 'tornillo']::text[]),
  ('si:agent-pod', 'si', 'agent-identity', array['agent-lifecycle-states', 'people-accounts', 'bot', 'avatar', 'ai-face', 'companion']::text[]),
  ('si:cashback', 'si', 'agentic-payments', array['commerce-finance', 'everyday-objects', 'refund', 'rebate', 'rewards', 'money-back']::text[]),
  ('si:lottery-ticket', 'si', 'agentic-payments', array['trending-culture', 'commerce-finance', 'raffle', 'lotto', 'prize-draw', 'sweepstakes']::text[]),
  ('si:noodle-bowl', 'si', 'food-dining', array['kitchen', 'everyday-objects', 'ramen', 'noodles', 'pasta', 'meal']::text[]),
  ('si:dinosaur', 'si', 'nature-animals', array['trending-culture', 't-rex', 'dino', 'prehistoric', 'paleontology']::text[]),
  ('si:fossil', 'si', 'nature-animals', array['ammonite', 'paleontology', 'archaeology', 'geology']::text[]),
  ('si:comb', 'si', 'personal-care', array['everyday-objects', 'hair-care', 'grooming', 'barber', 'styling']::text[]),
  ('si:hairbrush', 'si', 'personal-care', array['everyday-objects', 'hair-care', 'grooming', 'paddle-brush', 'styling']::text[]),
  ('si:hair-clipper', 'si', 'personal-care', array['everyday-objects', 'hair-care', 'grooming', 'barber', 'trimmer']::text[]),
  ('si:mascara', 'si', 'personal-care', array['trending-culture', 'cosmetics', 'beauty', 'makeup', 'eyelashes']::text[]),
  ('si:nail-polish', 'si', 'personal-care', array['trending-culture', 'cosmetics', 'beauty', 'manicure', 'nails']::text[]),
  ('material:smart_toy', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:robot', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:psychology', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:psychology_alt', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:memory', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:memory_alt', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:database', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:database_search', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:webhook', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:workflow', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:prompt_suggestion', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:model_training', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:network_intelligence', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:network_intelligence_history', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:network_intelligence_update', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:hub', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:schema', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:data_object', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:account_tree', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:auto_awesome', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:generating_tokens', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:token', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:dataset', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:dataset_linked', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:terminal', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:brain-circuit', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:brain-cog', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:brain', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:bot-message-square', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:messages-square', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:message-square-code', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:message-circle-code', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:scan-search', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:scan-eye', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:search-code', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:file-search', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:folder-search', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:workflow', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:circuit-board', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:waypoints', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:layers-3', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:blocks', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:binary', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:code-xml', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:database-zap', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:server-cog', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:network', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:router', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:plug-zap', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:wand-sparkles', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:menu', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:close', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_back', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_forward', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:chevron_left', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:chevron_right', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:expand_more', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:expand_less', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:home', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:search', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:settings', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:more_vert', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:more_horiz', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:apps', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:fullscreen', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:filter_list', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:sort', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:refresh', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:tab', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:drag_indicator', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_upward', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_downward', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:swap_vert', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:swap_horiz', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:undo', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:redo', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:menu_open', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:segment', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:density_medium', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:view_sidebar', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:dock_to_right', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:dock_to_left', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:grid_view', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:view_list', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:view_module', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:dashboard', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:splitscreen', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:picture_in_picture_alt', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:open_in_new', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:open_in_full', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:zoom_in', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:zoom_out', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:first_page', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:last_page', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:unfold_more', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:unfold_less', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:fullscreen_exit', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:double_arrow', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:subdirectory_arrow_right', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:launch', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('tabler:circle-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:circle-x', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:alert-triangle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:info-circle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:help-circle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:ban', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:clock', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:hourglass', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:loader-2', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:refresh', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:progress-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:bell', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:eye', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:eye-off', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:thumb-up', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:thumb-down', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:star', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:shield-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trophy', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:sparkles', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:power', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:toggle-right', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:bookmark', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:pinned', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:flag', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:archive', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trash', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:send', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:cloud-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:wifi', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:bolt', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:flame', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:link', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:lock', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:lock-open', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:key', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:mail-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:message-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:list-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:filter', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:sort-ascending', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trending-up', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trending-down', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:mood-smile', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:mood-sad', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:circle-dot', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:clipboard-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:rosette-discount-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:heart', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:alert-circle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[])
on conflict (icon_id) do update
set
  source_library = excluded.source_library,
  job_category = excluded.job_category,
  secondary_categories = excluded.secondary_categories,
  updated_at = timezone('utc', now());
