-- P0.02 taxonomy seed for the first three job-shaped collections.
-- Source of truth: lib/icon-taxonomy-seed.js

insert into public.icon_metadata (
  icon_id,
  source_library,
  job_category,
  secondary_categories
)
values
  ('material:smart_toy', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:robot', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:psychology', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:psychology_alt', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:memory', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:memory_alt', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:database', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:database_search', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:webhook', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:workflow', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:prompt_suggestion', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:model_training', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:network_intelligence', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:network_intelligence_history', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:network_intelligence_update', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:hub', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:schema', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:data_object', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:account_tree', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:auto_awesome', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:generating_tokens', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:token', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:dataset', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:dataset_linked', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:terminal', 'material', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:brain-circuit', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:brain-cog', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:brain', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:bot-message-square', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:messages-square', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:message-square-code', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:message-circle-code', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:scan-search', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:scan-eye', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:search-code', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:file-search', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:folder-search', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:workflow', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:circuit-board', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:waypoints', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:layers-3', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:blocks', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:binary', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:code-xml', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:database-zap', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:server-cog', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:network', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:router', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:plug-zap', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('lucide:wand-sparkles', 'lucide', 'ai-agent-workflows', array['ai', 'agents', 'automation']::text[]),
  ('material:menu', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:close', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_back', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_forward', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:chevron_left', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:chevron_right', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:expand_more', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:expand_less', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:home', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:search', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:settings', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:more_vert', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:more_horiz', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:apps', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:fullscreen', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:filter_list', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:sort', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:refresh', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:tab', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:drag_indicator', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_upward', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:arrow_downward', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:swap_vert', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:swap_horiz', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:undo', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:redo', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:menu_open', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:segment', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:density_medium', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:view_sidebar', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:dock_to_right', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:dock_to_left', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:grid_view', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:view_list', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:view_module', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:dashboard', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:splitscreen', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:picture_in_picture_alt', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:open_in_new', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:open_in_full', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:zoom_in', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:zoom_out', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:first_page', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:last_page', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:unfold_more', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:unfold_less', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:fullscreen_exit', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:double_arrow', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:subdirectory_arrow_right', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('material:launch', 'material', 'navigation-wayfinding', array['navigation', 'wayfinding', 'layout']::text[]),
  ('tabler:circle-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:circle-x', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:alert-triangle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:info-circle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:help-circle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:ban', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:clock', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:hourglass', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:loader-2', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:refresh', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:progress-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:bell', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:eye', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:eye-off', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:thumb-up', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:thumb-down', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:star', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:shield-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trophy', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:sparkles', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:power', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:toggle-right', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:bookmark', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:pinned', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:flag', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:archive', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trash', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:send', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:cloud-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:wifi', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:bolt', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:flame', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:link', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:lock', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:lock-open', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:key', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:mail-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:message-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:list-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:filter', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:sort-ascending', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trending-up', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:trending-down', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:mood-smile', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:mood-sad', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:circle-dot', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:clipboard-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:rosette-discount-check', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:heart', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[]),
  ('tabler:alert-circle', 'tabler', 'status-feedback', array['status', 'feedback', 'signals']::text[])
on conflict (icon_id) do update
set
  source_library = excluded.source_library,
  job_category = excluded.job_category,
  secondary_categories = excluded.secondary_categories,
  updated_at = timezone('utc', now());
